### ISSUE TITLE
Worth building openmm on win-32 py2?

### ISSUE THREAD

**Issue by rmcgibbo** [omnia-md/conda-recipes#127]
For python2, using MSVC2008, the CPU platform does not compile. This is a mixture of issues relating to bugs in MSVC2008 and the lack of AVX support. These probably could be worked around.

If I turn off the CPU platform, it will compile though. So, is it worth it to release a "crippled" build of OpenMM for omnia, or should we just not build a py2 build of OpenMM at all?

**Comment by rmcgibbo** [comment]
(related: https://github.com/pandegroup/openmm/issues/785)

**Comment by jchodera** [comment]
None of us use `win` support, so can't say. Maybe @peastman has ideas?

Would it have CUDA support compiled in too?  If so, it may not be so crippled on machines with NVIDIA GPUs.

**Comment by rmcgibbo** [comment]
Yeah, the CUDA platform compiles just fine.

**Comment by peastman** [comment]
We're talking about the set of people who want to use OpenMM as part of Omnia on a Windows computer with an NVIDIA GPU, and who for some reason don't want to use Python 3.  When you take the intersection of all those things, I suspect the number of people it covers is pretty tiny.

The OpenCL platform might be more useful, since that also covers AMD and Intel GPUs.  Still, I wonder how many people would really object if we just said, "Windows requires Python 3?"

**Comment by rmcgibbo** [comment]
> The OpenCL platform might be more useful, since that also covers AMD and Intel GPUs. Still, I wonder how many people would really object if we just said, "Windows requires Python 3?"

Okay. I think that's probably fine.
