### ISSUE TITLE
Move build script from jenkins server into github.

### ISSUE THREAD

**Issue by rmcgibbo** [omnia-md/conda-recipes#150]
@jchodera: now that the build is relatively stable, we should move the executable shell script from the jenkins config to a shell script in this repo, e.g. `.jenkins-linux-vagrant.sh`, and then change the jenkins config to just run the script.

https://jenkins.choderalab.org/job/conda-omnia-release-linux-vagrant/configure

**Comment by jchodera** [comment]
I'd love to do this, but we would have to discuss the security implications of doing so. Since this would effectively be able to launch external code within our firewall, we'd have to find some way to completely firewall off all of the build servers that the Jenkins master would have access to in order for it to be completely safe.  Or perhaps there's a simpler safe solution?

**Comment by rmcgibbo** [comment]
I don't see how it's any different than the current situation. I can put whatever they want in the `build.sh` files in this repo, and it'll get run on your machine. Anyone with commit access can do this. How is editing 
`.jenkins-linux-vagrant.sh` vs. `random-recipe/build.sh` any different?

The defense against this is that relatively few people have commit access to this repo, and they need to be trusted people.

**Comment by jchodera** [comment]
Good point.

**Comment by jchodera** [comment]
Actually, this likely means we will have to impose a more thorough review of recipe scripts we allow in this repo at the moment.  Would you be OK if only MSK people handled check-ins until we can resolve potential security issues?

**Comment by rmcgibbo** [comment]
LOL.

Okay, you should change the team/owner settings then.

**Comment by kyleabeauchamp** [comment]
Is Jenkins running in a semi safe VM anyway?  Imho we dont have enough
staff to do this ourselves.

**Comment by jchodera** [comment]
Jenkins is, but the slaves are not.

**Comment by marscher** [comment]
A nice tool for having versioning for jenkins jobs: https://wiki.jenkins-ci.org/display/JENKINS/Job+DSL+Plugin

You can also have the job definitions in a private repo, where only MSK folks can push too, but versioning is a must have.

**Comment by jchodera** [comment]
My feeling, now that we have appveyor building `win` and travis-ci supports `linux` and `osx`, is that we should migrate away from Jenkins completely, rather than switch to a version build system for Jenkins.  It's very much suboptimal to have us be the only people that can fix things, and the draconian hardware and software policies (which now include mandatory patching with limited advance warning and no control over timing of restarts) combined with ludicrous port blocking policies (I have to fill out some insane forms for every port I want to unblock, and even then, it is still unreliable) make it frustratingly difficult to maintain physical hardware here.

**Comment by rmcgibbo** [comment]
These seem like sunk costs, given that you've already set up the infrastructure. Getting linux packaging working on Travis-CI would be a lot of work, because we need to use an older glibc.

**Comment by jchodera** [comment]
The effort required to keep things running is not a sunk cost, nor is the
effort required to switch to a new build script system.

My point was that if we were going to switch to a new build script system,
it should be a cloud based system.

Good point about the older libraries.  We do have a docker version of the
VM in the works for the OpenMM core.  Is there a way to use that on Travis?

At worst, we could use a cloud based Jenkins system with EC2 instance
workers that are spun up on demand.

**Comment by rmcgibbo** [comment]
> At worst, we could use a cloud based Jenkins system with EC2 instance
workers that are spun up on demand.

Having played around with this, it's really _a lot_ more work.

>Good point about the older libraries.  We do have a docker version of the
VM in the works for the OpenMM core.  Is there a way to use that on Travis?

It looks like https://github.com/bioconda/recipes have set it up this way.

**Comment by rmcgibbo** [comment]
It's up to you. I am fine with the current system -- it works well enough. If you want to change it to something else, that's fine (they're your machines of course). But I suspect it will be nontrivial, and I won't be taking the lead on the porting.

**Comment by kyleabeauchamp** [comment]
FWIW, I've been following the bioconda team for several weeks now.  There's
been a lot of changes recently, but I imagine things might stabilize in a
few weeks.  I think a reasonable approach might be to wait a bit and see
how well things go for them in the next month or so.

AFAIK, their builds are based on a Centos 5 machine.  However, CUDA only
supports Centos 6 and 7.

Finally, one of their lead developers is also the author of snakemake,
which is awesome and worth checking out.
