### ISSUE TITLE
Lots of stuff broken with conda-build 1.18

### ISSUE THREAD

**Issue by rmcgibbo** [omnia-md/conda-recipes#338]
The rules for when numpy is included in the build string changed https://github.com/conda/conda-build/pull/573

**Comment by jchodera** [comment]
Ugh.

**Comment by jchodera** [comment]
Can we pin the version to fix that?

**Comment by rmcgibbo** [comment]
We could, but I think the new behavior is an improvement. We just have to figure out how to work with it.

**Comment by jchodera** [comment]
How much stuff is broken that needs to be upgraded/fixes?

**Comment by jchodera** [comment]
http://binstar.org now redirects to the crazy new https://anaconda.org/ "Anaconda Cloud" page.

**Comment by mpharrigan** [comment]
lol their logo looks like 80% of the proposed omnia logos

**Comment by mpharrigan** [comment]
Per some debugging with the mdtraj recipe, the solution is to add `-numpy x.x` to both the `build` and `run` section. Literally `x.x`

This *is* an improvement. Packages that only import numpy only need to be built once. Packages that link against the numpy c api will work as before (with the addition of x.x to the recipes)

**Comment by rmcgibbo** [comment]
Fixing this now.

**Comment by marscher** [comment]
Due to this changes in conda-build we ended up in having binaries which are generic (includes only targeted Python version like 'linux-64/bhmm-0.5.1-py34_0.tar.bz2' uploaded 8 days before this post) and some which specify the Numpy version (like inux-64/bhmm-0.5.1-np19py34_0.tar.bz2).

Actually it seems like a duplication and I wonder what is the cause for that. If you install a package with duplicate candidates, conda takes forever generating the hint message, that there are duplicates. So I guess we should fix this - shall I open up a new issue for that one?

**Comment by mpharrigan** [comment]
That's just a matter of deleting the older, generic packages from binstar/whatever-they-call-it-now, no?

**Comment by rmcgibbo** [comment]
@marscher i deleted the files that don't properly specify the number version, so it should be fixed now.

**Comment by marscher** [comment]
I was just wondering why the generic packages were more recent than the version specific ones.

**Comment by rmcgibbo** [comment]
Fixed.
