### ISSUE TITLE
handling pre-releases (or having more than one label in channel)

### ISSUE THREAD

**Issue by marscher** [omnia-md/conda-recipes#445]
Situation is, that we want to have multiple release candidate versions to be available on conda/label/pre (so these binaries will not show up in the main channel and therefore will be offered as upgrades).

The nice thing about pre-releases is that we do not pollute the channel with several micro releases until a new minor/major release is stable. I propose the label "pre" for these builds. If we use conventional version numbers (PEP440) for RCs, eg 2.1rc1, we can automatically handle these and upload them to the pre label of the channel.

These can then be simply installed with conda with this command:
``` conda install -c omnia/label/pre pkg ```

I've started a branch to handle this (support_pre_releases). Please note that the conda-build-all tool didn't support checking multiple labels/channels for existing packages. So this has also been added there.

Since Frank already asked my to provide RCs of pyemma on omnia, I've manually moved the packages from main to pre label. But because omnia-build-all only checks the main channel, it causes errors now (file already exists). This should also be circumvented on the feature branch.

Please let me know what you think.

cc: @franknoe, @rmcgibbo, @jchodera 
fyi: @clonker

**Comment by franknoe** [comment]
I think this would be useful. @jchodera  or @rmcgibbo  can you look into this?

**Comment by marscher** [comment]
The merge was actually a test (which could only be performed in case PR is set to false and the packages to be build are missing). I've reverted it again, since it fails with the docker image on Linux (the semantics of conda-build-all changed a bit).

**Comment by jchodera** [comment]
Please be very careful here since you have the potential of breaking
everything and polluting the channel.

I would like to see you demonstrate this with a separate channel first. Can
you set up your own fork to run Travis and appveyor separately and
illustrate that this works as expected  for both standard and prerelease
packages?

I certainly agree with the utility and elegance of this approach, but our
earlier tests suggested that conda would ignore channel labels and pull
whichever package was most recently uploaded regardless of label. We need
to know this has been fixed.

Also, can you do some experimentation and figure out:
* can someone have the same package name installed from BOTH main and pre
labels, or are they mutually exclusive (as we hope)?
* what happens when you ask conda to upgrade the package or install the
main package?
* how can we specify dependencies for pre packages in meta.YAML files?

**Comment by marscher** [comment]
On 24.02.2016 15:46, John Chodera wrote:
> Please be very careful here since you have the potential of breaking
> everything and polluting the channel.
> 
> I would like to see you demonstrate this with a separate channel first. Can
> you set up your own fork to run Travis and appveyor separately and
> illustrate that this works as expected for both standard and prerelease
> packages?
Sure, will do.
> 
> I certainly agree with the utility and elegance of this approach, but our
> earlier tests suggested that conda would ignore channel labels and pull
> whichever package was most recently uploaded regardless of label. We need
> to know this has been fixed.
It seems like. We've used this pattern already. But manually moving the
uploading packages to pre is huge hassle.
> 
> Also, can you do some experimentation and figure out:
> * can someone have the same package name installed from BOTH main and pre
> labels, or are they mutually exclusive (as we hope)?
They are. The trick is to manually specify the label one wants to
install from during issuing the install command.
> * what happens when you ask conda to upgrade the package or install the
> main package?
As expected: installs from the configured channel (which defaults to main).
> * how can we specify dependencies for pre packages in meta.YAML files?
Don't know if that is possible without explicitly activating the pre
label, which would then drag in all pre-releases available.

**Comment by marscher** [comment]
btw a simple fork would not be sufficient, because the access token wont
be available.

So to "demonstrate" that this works, I have to "clone" really everything,

**Comment by jchodera** [comment]
> btw a simple fork would not be sufficient, because the access token wont
be available.

I meant that you should do this for a different anaconda cloud account and channel.  You can generate your own binstar token that works in your own forked repo.

> Don't know if that is possible without explicitly activating the pre label, which would then drag in all pre-releases available.

Would we still keep the `*-dev` versions of packages then?  Otherwise, I don't see a way automated travis testing could use latest package versions.

**Comment by marscher** [comment]
On 24.02.2016 16:42, John Chodera wrote:
>     btw a simple fork would not be sufficient, because the access token wont
>     be available.
> 
> I meant that you should do this for a different anaconda cloud account
> and channel. You can generate your own binstar token that works in your
> own forked repo.
Right.
> 
>     Don't know if that is possible without explicitly activating the pre
>     label, which would then drag in all pre-releases available.
> 
> Would we still keep the |*-dev| versions of packages then? Otherwise, I
> don't see a way automated travis testing could use latest package versions.
Dev version (or nightly builds) are different thing than pre-releases.
These are still separated, because the package name is different (eg.
openmm-dev wont collide with openmm in pre channel, since dev is located
in main)

**Comment by rmcgibbo** [comment]
This all sounds good. I would be fine with this, @marscher.
