### ISSUE TITLE
Shiftx2 got sent to "pre" label

### ISSUE THREAD

**Issue by mpharrigan** [omnia-md/conda-recipes#467]
I haven't been keeping up with this, but I would hope that new recipes would be put in the main label by default.

cc #466 

Why did this get sent to the "pre" label?

**Comment by mpharrigan** [comment]
cc #445

**Comment by mpharrigan** [comment]
I'm manually changing the label from pre to main on each of the bz2 files

**Comment by jchodera** [comment]
Tagging @marscher : Any idea what happened here?  Did you make some changes to the build script that may have caused this?

**Comment by marscher** [comment]
I think so. The check for a package to go to "pre" is a setuptools related version class attribute name "pre-release", which in this case is true for a version number tagged "A" for alpha. So this is actually expected behaviour for this kind over version number scheme. How do we want to tag releases to be public or restrict them to testing community? 
This question arises because we somehow need to automatize how to treat pre-releases.

**Comment by mpharrigan** [comment]
Ok, shiftx2 doesn't follow pep440 at all, so we'll just have to keep an eye out in this instance whenever we try to rebuild it (which shouldn't be often)

An alternative would be to give the conda package a different, pep440 compliant version string that differs from the upstream number

**Comment by marscher** [comment]
We could add a blacklist file for non pep440 compliant packages.
