### ISSUE TITLE
Builds failing due to Latex

### ISSUE THREAD

**Issue by jlmaccal** [omnia-md/conda-recipes#725]
I'm using similar infrastructure to build cuda-specific versions of OpenMM and MELD for my lab (see github.com/maccallumlab/meld-pkg).

Things have been working great until recently an error is occurring while building the OpenMM docs: 
```
(/usr/local/texlive/2015/texmf-dist/tex/latex/psnfss/times.sty)
! LaTeX Error: File `fncychap.sty' not found.
Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)
```

Has something changed in the build box or some other `omnia-md/conda-recipes` package that OpenMM uses during install?

**Comment by Lnaden** [comment]
Yes. Its related to the Sphinx version. I'm working on #723 to try and fix the problem here on the omnia-md channel.

But the OpenMM builds you get from the `omnia` channel should not have been affected by this yet unless you are also pulling down the `sphinxcontrib-autodoc_doxygen` package which did update with #721 earlier today. If you have a TeX manager installed, you should just be able to install `fncychap` and `tabulary`. You could also download `sphinxcontrib-autodoc_doxygen` 0.3.1 to go back to the old version.

**Comment by Lnaden** [comment]
There might be more packages that are missing. I'm working on compiling a list of them in #723 when the builds fail

**Comment by Lnaden** [comment]
I think this might bring the larger question: How much should we try to include LaTeX packages with OpenMM deployment through the conda channel?

**Comment by Lnaden** [comment]
If this is still a problem, I think you will have to download the following TeX packages locally due to Sphinx changes:

* fncychap
* tabulary
* capt-of
* eqparbox
* environ
* trimspaces

Otherwise I should have fixed everything else.

**Comment by Lnaden** [comment]
On a related note, the current `meld-plugin` build is failing here since it requires `openmm-dev`. I'm guessing that is a legacy thing and could probably be changed to just `openmm`?

**Comment by jlmaccal** [comment]
Actually, the MELD plugin is no longer a thing as it’s been integrated into the main MELD package. I really need to update the recipes here.

**Comment by Lnaden** [comment]
I think I fixed this a while back. Re-open if you are still having issues though!
