### ISSUE TITLE
Centos5 EOL

### ISSUE THREAD

**Issue by jlmaccal** [omnia-md/conda-recipes#763]
So, apparently CentOS 5 went EOL at the end of March. Obviously, we should consider updating at some point.

None of the `yum` repositories in our current `omnia-build-box` are correct any more. This causes problems for us with MELD, as we use `awscli` to upload our documentation, which in turn, requires `groff` to be installed through `yum`.

@jchodera Could you have a look at this [thread](https://www.centos.org/forums/viewtopic.php?t=62106)? I think we just need to edit the repository configuration in the Docker image, but I'm not quite sure how to do that.

**Comment by jchodera** [comment]
> So, apparently CentOS 5 went EOL at the end of March. Obviously, we should consider updating at some point.

@Lnaden is already on it! See #761, which updates to a CentOS 6 box based on the [`conda-forge/linux-anvil`](https://github.com/conda-forge/docker-images/tree/master/linux-anvil).

> None of the yum repositories in our current omnia-build-box are correct any more. 
> This causes problems for us with MELD, as we use awscli to upload our documentation, which in turn, requires groff to be installed through yum.

Does that mean your recipe needs to do a `yum install ...` to pull in packages that aren't conda-installable? If so, we should add those to the new docker image if possible, since I don't think recipes are *supposed* to have sudo access to do this. 

> @jchodera Could you have a look at this thread? I think we just need to edit the repository configuration in the Docker image, but I'm not quite sure how to do that.

I think we should focus on completing the CentOS 6 build framework update this week, since this is necessary to also let packages start to migrate to `conda-forge`. Be sure to let @Lnaden know what extra `yum` packages you need installed that aren't available via `conda` (including `conda-forge`, which will now become a dependency). 

@Lnaden will post the whole roadmap for the staged migration to `conda-forge` shortly.

**Comment by jlmaccal** [comment]
> @Lnaden is already on it! See #761, which updates to a CentOS 6 box based on the conda-forge/linux-anvil.

Great! I missed that.

> Does that mean your recipe needs to do a yum install ... to pull in packages that aren't conda-installable? If so, we should add those to the new docker image if possible, since I don't think recipes are supposed to have sudo access to do this.

Well, empirically, they do have root within the docker image. We need to have `groff` installed, so if that can be added to the images.

**Comment by jchodera** [comment]
> Well, empirically, they do have root within the docker image. 

Sure, but you can't even `conda build` your recipe locally on your own machine without dropping to root. conda recipes aren't supposed to require root access---that's why we have to install any dependencies through `conda` or---worst case---via the build framework.

> We need to have groff installed, so it would be great if that can be added to the images.

Great! Can you create a separate issue listing `groff` and any other packages you needed added to the build framework? In principle, this could be simply built as an anaconda package, like we do with other dependencies---others [have done this](https://anaconda.org/search?q=groff)---but it seems simple enough to add to the build image given that we're also adding latex and friends.

**Comment by Lnaden** [comment]
I already have a loose outline in the PR's README file [here](https://github.com/omnia-md/conda-recipes/blob/90df632ebdd7054c5d75635c9f7e617f56fa0ad7/README.md). Feel free to add any suggestions to it!

**Comment by jlmaccal** [comment]
@jchodera @Lnaden I'm not sure the best place for this discussion, but I'll try here rather than opening an issue.

Can you give an overview of how the conda-forge system works? Are our packages going to end up in the conda-forge channel, or are we just using their infrastructure? 

Is there a good overview anywhere? I find the official conda-forge website to be pretty opaque.

**Comment by jchodera** [comment]
> Can you give an overview of how the conda-forge system works? Are our packages going to end up in the conda-forge channel, or are we just using their infrastructure?

Can you wait another day or two for us to assemble the omnia roadmap? You don't have to worry for the moment, since we aren't going to migrate any packages now. We're just going to make it possible for packages that don't depend on OpenMM to migrate to `conda-forge` without breaking everything. We'll later make it possible for packages that *do* depend on OpenMM to migrate, but that's still some time down the road.

> Is there a good overview anywhere? I find the official conda-forge website to be pretty opaque.

Hm, I thought their [docs](http://conda-forge.github.io/docs/) were pretty good.

**Comment by Lnaden** [comment]
We are now on a variant of the conda-forge CentOS6 image, I think this issue can be safely closed.
